apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-sls-group
spec:
  targetNamespaces:
    - ibm-sls
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-sls
  namespace: ibm-sls
spec:
  channel: 3.x
  installPlanApproval: Automatic
  name: ibm-sls
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
